version: '3'
services:
  blockchain:
    container_name: blockchain
    build:
      context: btcd/
    volumes:
      - shared:/rpc
      - bitcoin:/data
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - DEBUG
      - MINING_ADDRESS
    restart: on-failure
    entrypoint: ["./start-btcd.sh"]

  lnd:
    build:
      context: lnd/
    container_name: lnd
    volumes:
      - shared:/rpc
      - lnd:/root/.lnd
      - ./lnd/start-lnd.sh:/start-lnd.sh
      - ./rpc.txt:/rpc.txt
    ports:
      - 9735:9735
      - 10009:10009
    depends_on:
      - blockchain
    entrypoint: ["sh", "/start-lnd.sh"]

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  lndhub:
    build:
      context: lndhub/
    container_name: lndhub
    user: root
    volumes:
      - lnd:/root/.lnd
      - lndhub:/root/.lndhub
    ports:
      - 3000:3000
    depends_on:
      - lnd
      - redis
    environment:
      - LND_ADMIN_MACAROON_FILE=/root/.lnd/data/chain/bitcoin/mainnet/admin.macaroon
      - LND_CERT_FILE=/root/.lnd/tls.cert
      - CONFIG={"enableUpdateDescribeGraph":false,"postRateLimit":100,"rateLimit":200,"forwardReserveFee":0.01,"intraHubFee":0.003,"redis":{"port":6379,"host":"redis","family":4,"password":"","db":0},"lnd":{"url":"lnd:10009","password":""}}

volumes:
  lnd:
    driver: local
  redis_data:
    driver: local
  lndhub:
    driver: local
  bitcoin:
    driver: local
  shared:
    driver: local