version: '3'
services:
  lnd:
    image: lightninglabs/lnd:v0.14.1-beta
    container_name: lnd
    volumes:
      - lnd_data:/root/.lnd
      - ./start-lnd.sh:/start-lnd.sh
      - ./rpc.txt:/rpc.txt
    ports:
      - 9735:9735
      - 10009:10009
    entrypoint: ["sh", "/start-lnd.sh", "--wallet-unlock-password-file", "/rpc.txt"]

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  lndhub:
    image: bluewalletorganization/lndhub:v1.3.0
    container_name: lndhub
    volumes:
      - lnd_data:/root/.lnd
      - lndhub_data:/root/.lndhub
    ports:
      - 3000:3000
    depends_on:
      - lnd
      - redis
    environment:
      - LND_ADMIN_MACAROON_FILE=/root/.lnd/data/chain/bitcoin/testnet/admin.macaroon
      - LND_CERT_FILE=/root/.lnd/tls.cert
    # command: ["command-to-start-lndhub"]

volumes:
  lnd_data:
    driver: local
  redis_data:
    driver: local
  lndhub_data:
    driver: local